import { FAMILIES, type Family } from "./schema";

/** Human-readable names for each shader family, shared across the UI. */
export const FAMILY_LABELS: Record<Family, string> = {
  mesh: "Mesh gradient",
  silk: "Silk waves",
  aurora: "Aurora",
  smoke: "Smoke",
  orbs: "Bokeh orbs",
  grid: "Pulse grid",
  rings: "Ripple rings",
  rays: "Light rays",
  cells: "Drift cells",
  ribbons: "Ribbon bands",
  halftone: "Halftone print",
  nebula: "Star nebula",
  topo: "Contour lines",
  lava: "Lava lamp",
  kaleido: "Kaleidoscope",
  hex: "Hex tiles",
  weave: "Wave weave",
  spiral: "Spiral arms",
  prism: "Prism strips",
  breath: "Breathing glow",
  rain: "Rain streaks",
  chevron: "Chevron flow",
  sweep: "Gradient sweep",
  marble: "Liquid marble",
  caustics: "Light caustics",
  ink: "Ink blooms",
  checker: "Kinetic checker",
  tunnel: "Retro tunnel",
  maze: "Circuit maze",
  orbitals: "Orbital paths",
  plasma: "Color plasma",
  glitch: "Digital glitch",
  equalizer: "Spectrum bars",
  radar: "Radar sweep",
  hologram: "Hologram",
  accretion: "Accretion disk",
  fractals: "Fractals",
  noise: "Noise",
  waves: "Waves",
  singularity: "Singularity",
  warpedNoise: "Warped noise",
};

export const familyItems = FAMILIES.map((f) => ({
  value: f,
  label: FAMILY_LABELS[f],
}));
