import { FAMILIES, type Family } from "./schema";

/** Human-readable names for each shader family, shared across the UI. */
export const FAMILY_LABELS: Record<Family, string> = {
  mesh: "Mesh gradient",
  silk: "Silk waves",
  aurora: "Aurora",
  smoke: "Smoke",
  orbs: "Bokeh orbs",
  grid: "Pulse grid",
  rings: "Ripple rings",
  rays: "Light rays",
  cells: "Drift cells",
  ribbons: "Ribbon bands",
  halftone: "Halftone print",
  nebula: "Star nebula",
  topo: "Contour lines",
  lava: "Lava lamp",
  kaleido: "Kaleidoscope",
  hex: "Hex tiles",
  weave: "Wave weave",
  spiral: "Spiral arms",
  prism: "Prism strips",
  breath: "Breathing glow",
  rain: "Rain streaks",
  chevron: "Chevron flow",
  sweep: "Gradient sweep",
  marble: "Liquid marble",
  caustics: "Light caustics",
  ink: "Ink blooms",
  checker: "Kinetic checker",
  tunnel: "Retro tunnel",
  maze: "Circuit maze",
  orbitals: "Orbital paths",
  plasma: "Color plasma",
  glitch: "Digital glitch",
  equalizer: "Spectrum bars",
  radar: "Radar sweep",
  hologram: "Hologram",
  accretion: "Accretion disk",
  fractals: "Fractals",
  noise: "Noise",
  waves: "Waves",
  singularity: "Singularity",
  warpedNoise: "Warped noise",
  liquidMetal: "Liquid metal",
  iridescentGlass: "Iridescent glass",
  ribbonSculpture: "Ribbon sculpture",
  architecture: "Architectural tunnel",
  constellation: "Constellation trails",
  luminousOrbits: "Luminous orbits",
  moire: "Optical moiré",
  nacreFlow: "Nacre currents",
  velvetFlow: "Velvet flow",
  glassVeil: "Glass veils",
  prismField: "Prismatic field",
  satinDunes: "Satin dunes",
  metallicWaves: "Metallic waves",
  silkCurrent: "Silk currents",
  aquaVeil: "Aqueous veils",
  mistLayers: "Layers of mist",
  magneticFlow: "Magnetic currents",
  foldedCanopy: "Folded canopy",
  contourRelief: "Contour relief",
  floatingVeils: "Floating veils",
  prismCurtain: "Prismatic curtains",
  lightPainting: "Light painting",
  spectralRibbons: "Spectral ribbons",
  causticPool: "Caustic pool",
  eclipseHalo: "Eclipse halo",
  starVortex: "Stellar vortex",
  dustDrift: "Drifting dust",
  cutPaper: "Paper cut landscapes",
  opArtWeave: "Optical weave",
  neonLattice: "Neon lattice",
  auroraCanopy: "Aurora canopy",
  tidalGlass: "Tidal glass",
  twilightHaze: "Twilight haze",
  cloudSea: "Sea of clouds",
  emberVeil: "Amber veils",
  forestLight: "Canopy light",
  rainWindow: "Rain on glass",
  opalWash: "Opal washes",
  lightColumns: "Columns of light",
  lunarDunes: "Moonlit dunes",
  inkWash: "Ink washes",
  deepOcean: "Ocean light",
};

export const familyItems = FAMILIES.map((f) => ({
  value: f,
  label: FAMILY_LABELS[f],
}));
